USE movies;

SELECT TITLE, YEAR, STUDIONAME, ADDRESS
FROM MOVIE
         JOIN STUDIO ON STUDIONAME = NAME
WHERE INCOLOR = 'Y';

SELECT M1.TITLE, M1.LENGTH
FROM MOVIE M1,
     MOVIE M2
WHERE M2.TITLE = 'Star Wars'
  AND M1.LENGTH > M2.LENGTH;

SELECT MOVIESTAR.NAME, MOVIE.TITLE
FROM MOVIESTAR
         JOIN STARSIN ON MOVIESTAR.NAME = STARSIN.STARNAME
         JOIN MOVIE on MOVIE.TITLE = STARSIN.MOVIETITLE and YEAR = MOVIEYEAR
WHERE MOVIESTAR.GENDER = 'F'
  AND MOVIE.STUDIONAME = 'MGM';

SELECT TITLE, YEAR
FROM MOVIE
WHERE INCOLOR = 'Y'
UNION
SELECT MOVIETITLE, MOVIEYEAR
FROM STARSIN;

SELECT NAME, ADDRESS
FROM MOVIESTAR
WHERE GENDER = 'F'
INTERSECT
SELECT NAME, ADDRESS
FROM MOVIEEXEC
WHERE NETWORTH > 10000000;

(SELECT NAME, ADDRESS
 FROM MOVIESTAR)
EXCEPT
(SELECT NAME, ADDRESS
 FROM MOVIEEXEC)
ORDER BY ADDRESS;

-- Problem 1
SELECT MOVIESTAR.NAME
FROM MOVIESTAR
         JOIN STARSIN S ON MOVIESTAR.NAME = S.STARNAME
WHERE MOVIESTAR.GENDER = 'F'
  AND S.MOVIETITLE = 'Terms of Endearment';

-- Problem 2
SELECT MOVIESTAR.NAME
FROM MOVIESTAR
         JOIN STARSIN S on MOVIESTAR.NAME = S.STARNAME
         JOIN MOVIE M on M.TITLE = S.MOVIETITLE and M.YEAR = S.MOVIEYEAR
WHERE S.MOVIEYEAR = 1995
  AND M.STUDIONAME = 'MGM';