USE ships;

SELECT DISTINCT BATTLE
FROM OUTCOMES
WHERE RESULT = 'sunk';

-- Problem 1
SELECT NAME
FROM SHIPS
         JOIN CLASSES C on C.CLASS = SHIPS.CLASS
WHERE C.DISPLACEMENT > 35000;

-- Problem 2
SELECT NAME, C.DISPLACEMENT, C.NUMGUNS
FROM SHIPS
         JOIN CLASSES C on C.CLASS = SHIPS.CLASS
         JOIN OUTCOMES O on SHIPS.NAME = O.SHIP
WHERE O.BATTLE = 'Guadalcanal';

-- Problem 3
SELECT DISTINCT C1.COUNTRY
FROM CLASSES C1
         JOIN CLASSES C2 ON C2.COUNTRY = C1.COUNTRY
WHERE C1.TYPE = 'bc'
  AND C2.TYPE = 'bb';

-- Problem 4
SELECT DISTINCT O1.SHIP
FROM OUTCOMES O1
         JOIN OUTCOMES O2 ON O1.SHIP = O2.SHIP
WHERE O1.BATTLE != O2.BATTLE;