-- Problem 1
USE movies;

-- 1.1
SELECT TITLE, YEAR, STUDIONAME, STUDIO.ADDRESS
FROM MOVIE
         INNER JOIN STUDIO on NAME = MOVIE.STUDIONAME
WHERE MOVIE.LENGTH > 120;

-- 1.2
SELECT STUDIO.NAME, STARSIN.STARNAME
FROM STUDIO
         INNER JOIN MOVIE on STUDIO.NAME = MOVIE.STUDIONAME
         INNER JOIN STARSIN on MOVIE.TITLE = STARSIN.MOVIETITLE and MOVIE.YEAR = STARSIN.MOVIEYEAR
ORDER BY STUDIO.NAME;

-- Using GROUP BY
SELECT STUDIO.NAME, STRING_AGG(TRIM(STARSIN.STARNAME), ', ')
FROM STUDIO
         INNER JOIN MOVIE on STUDIO.NAME = MOVIE.STUDIONAME
         INNER JOIN STARSIN on MOVIE.TITLE = STARSIN.MOVIETITLE and MOVIE.YEAR = STARSIN.MOVIEYEAR
GROUP BY STUDIO.NAME
ORDER BY STUDIO.NAME;

-- 1.3
SELECT DISTINCT MOVIEEXEC.NAME
FROM STARSIN
         INNER JOIN MOVIE on MOVIE.TITLE = STARSIN.MOVIETITLE and MOVIE.YEAR = STARSIN.MOVIEYEAR
         INNER JOIN MOVIEEXEC on MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
WHERE STARNAME = 'Harrison Ford';

-- 1.4
SELECT DISTINCT STARNAME
FROM STARSIN
         INNER JOIN MOVIE on MOVIE.TITLE = STARSIN.MOVIETITLE and MOVIE.YEAR = STARSIN.MOVIEYEAR
WHERE STUDIONAME = 'MGM';

-- 1.5
SELECT MOVIEEXEC.NAME, M1.TITLE
FROM MOVIEEXEC
         INNER JOIN MOVIE M1 ON MOVIEEXEC.CERT# = M1.PRODUCERC#
         INNER JOIN MOVIE M2 ON MOVIEEXEC.CERT# = M2.PRODUCERC#
WHERE M2.TITLE = 'Star Wars';

-- 1.6
SELECT NAME
FROM MOVIESTAR
         LEFT OUTER JOIN STARSIN on MOVIESTAR.NAME = STARSIN.STARNAME
WHERE STARSIN.STARNAME IS NULL;


-- Problem 2
USE pc;

-- 2.1
SELECT DISTINCT product.model, pc.price
FROM product
         LEFT OUTER JOIN pc ON product.model = pc.model
WHERE product.type = 'PC';

-- 2.2
SELECT product.model, product.maker, product.type
FROM product
         LEFT OUTER JOIN laptop on product.model = laptop.model
         LEFT OUTER JOIN pc on product.model = pc.model
         LEFT OUTER JOIN printer on product.model = printer.model
WHERE laptop.model IS NULL
  AND pc.model IS NULL
  AND printer.model IS NULL;


-- Problem 3
USE ships;

-- 3.1
SELECT NAME, CLASSES.COUNTRY, CLASSES.NUMGUNS, LAUNCHED
FROM SHIPS
         INNER JOIN CLASSES on CLASSES.CLASS = SHIPS.CLASS;

-- 3.2
SELECT DISTINCT OUTCOMES.SHIP
FROM OUTCOMES
         INNER JOIN BATTLES on BATTLES.NAME = OUTCOMES.BATTLE
WHERE YEAR(BATTLES.DATE) = 1942;