USE movies;

SELECT ADDRESS
FROM STUDIO
WHERE NAME = 'MGM';

SELECT BIRTHDATE
FROM MOVIESTAR
WHERE NAME = 'Sandra Bullock';

SELECT NAME
FROM MOVIESTAR
WHERE NAME IN (
    SELECT STARNAME
    FROM STARSIN
    WHERE MOVIEYEAR = 1980
      AND MOVIETITLE LIKE '%Empire%'
);

SELECT NAME
FROM MOVIEEXEC
WHERE NETWORTH > 10000000;

SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'M'
   OR ADDRESS = 'Malibu';
